# ~/.tmuxinator/weekend.yml
# you can make as many tabs as you wish...

project_name: MyAwesomeProject
project_root: ~/Sites/
pre: rbenv local 1.9.3-p194; powder unlink; powder link; powder open
tabs:
  - editor:
      layout: main-vertical
      panes:
        - vim .
        - #empty, will just run plain bash
  - console:  rails c
  - cucumber:
      layout: main-horizontal
      panes:
        - cd features; vim .
        - cucumber features/
  - shell: git pull
  - log: tail -f log/development.log

